##
##  Makefile -- Build procedure for sample golang Apache module
##  Autogenerated via ``apxs -n golang -g''.
##

builddir=.
top_srcdir=/etc/httpd
top_builddir=/usr/lib64/httpd
include /usr/lib64/httpd/build/special.mk

#   the used tools
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

.SUFFIXES: .go

.go.slo:
	$(LIBTOOL) --mode=compile gccgo $(ALL_CFLAGS) $(ALL_CPPFLAGS) $(SHLTCFLAGS) -c $< && touch $@

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_golang.o mod_golang.lo mod_golang.slo mod_golang.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/golang

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

