/* 
**  mod_golang.c -- Apache sample golang module
**  [Autogenerated via ``apxs -n golang -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_golang.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /golang in as follows:
**
**    #   httpd.conf
**    LoadModule golang_module modules/mod_golang.so
**    <Location /golang>
**    SetHandler golang
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /golang and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/golang 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_golang.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

extern int go_add(int, int) __asm__ ("main.Add");

/* The sample content handler */
static int golang_handler(request_rec *r)
{
    if (strcmp(r->handler, "golang")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rprintf(r, "The sample page from mod_golang.c said: %d\n", go_add(20, 22));
    return OK;
}

static void golang_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(golang_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA golang_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    golang_register_hooks  /* register hooks                      */
};

